### ISSUE TITLE
Not An Issue - Make This for MCPE?

### ISSUE THREAD

**Issue by LagHD** [gtavbeastaya/BungeeQueue#1]
I know you might be asking why the hell I created this here if it's not an issue but for some reason it won't let me make make a PR so anyways:
Could you make an MCPE Version of this plugin?
It'd be really cool, thanks!

**Comment by gtavbeastaya** [comment]
I don't really pay attention to PE and the pocket edition is written in C++, not java, nor is there any proper modding api for the pocket edition which makes writing plugins/mods very hard.
